// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: proto/speculate.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnrollRequest initiates enrollment of a target repository.
type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// repository in "owner/repo" format
	Repository    string `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_proto_speculate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_speculate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_proto_speculate_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

// EnrollResponse represents the result of enrolling a repository.
type EnrollResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Repository          string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	AlignmentPercentage int32                  `protobuf:"varint,2,opt,name=alignment_percentage,json=alignmentPercentage,proto3" json:"alignment_percentage,omitempty"`
	IssueUrl            string                 `protobuf:"bytes,3,opt,name=issue_url,json=issueUrl,proto3" json:"issue_url,omitempty"`
	StatusMessage       string                 `protobuf:"bytes,4,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_proto_speculate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_speculate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_proto_speculate_proto_rawDescGZIP(), []int{1}
}

func (x *EnrollResponse) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *EnrollResponse) GetAlignmentPercentage() int32 {
	if x != nil {
		return x.AlignmentPercentage
	}
	return 0
}

func (x *EnrollResponse) GetIssueUrl() string {
	if x != nil {
		return x.IssueUrl
	}
	return ""
}

func (x *EnrollResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

// EnrollmentRecord represents the persisted state of an enrolled repository.
type EnrollmentRecord struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Repository          string                 `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	AlignmentPercentage int32                  `protobuf:"varint,2,opt,name=alignment_percentage,json=alignmentPercentage,proto3" json:"alignment_percentage,omitempty"`
	IssueUrl            string                 `protobuf:"bytes,3,opt,name=issue_url,json=issueUrl,proto3" json:"issue_url,omitempty"`
	EnrolledAtUnix      int64                  `protobuf:"varint,4,opt,name=enrolled_at_unix,json=enrolledAtUnix,proto3" json:"enrolled_at_unix,omitempty"`
	LastEvaluatedAtUnix int64                  `protobuf:"varint,5,opt,name=last_evaluated_at_unix,json=lastEvaluatedAtUnix,proto3" json:"last_evaluated_at_unix,omitempty"`
	StatusMessage       string                 `protobuf:"bytes,6,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *EnrollmentRecord) Reset() {
	*x = EnrollmentRecord{}
	mi := &file_proto_speculate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollmentRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollmentRecord) ProtoMessage() {}

func (x *EnrollmentRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_speculate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollmentRecord.ProtoReflect.Descriptor instead.
func (*EnrollmentRecord) Descriptor() ([]byte, []int) {
	return file_proto_speculate_proto_rawDescGZIP(), []int{2}
}

func (x *EnrollmentRecord) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *EnrollmentRecord) GetAlignmentPercentage() int32 {
	if x != nil {
		return x.AlignmentPercentage
	}
	return 0
}

func (x *EnrollmentRecord) GetIssueUrl() string {
	if x != nil {
		return x.IssueUrl
	}
	return ""
}

func (x *EnrollmentRecord) GetEnrolledAtUnix() int64 {
	if x != nil {
		return x.EnrolledAtUnix
	}
	return 0
}

func (x *EnrollmentRecord) GetLastEvaluatedAtUnix() int64 {
	if x != nil {
		return x.LastEvaluatedAtUnix
	}
	return 0
}

func (x *EnrollmentRecord) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

var File_proto_speculate_proto protoreflect.FileDescriptor

const file_proto_speculate_proto_rawDesc = "" +
	"\n" +
	"\x15proto/speculate.proto\x12\tspeculate\"/\n" +
	"\rEnrollRequest\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\"\xa7\x01\n" +
	"\x0eEnrollResponse\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x121\n" +
	"\x14alignment_percentage\x18\x02 \x01(\x05R\x13alignmentPercentage\x12\x1b\n" +
	"\tissue_url\x18\x03 \x01(\tR\bissueUrl\x12%\n" +
	"\x0estatus_message\x18\x04 \x01(\tR\rstatusMessage\"\x88\x02\n" +
	"\x10EnrollmentRecord\x12\x1e\n" +
	"\n" +
	"repository\x18\x01 \x01(\tR\n" +
	"repository\x121\n" +
	"\x14alignment_percentage\x18\x02 \x01(\x05R\x13alignmentPercentage\x12\x1b\n" +
	"\tissue_url\x18\x03 \x01(\tR\bissueUrl\x12(\n" +
	"\x10enrolled_at_unix\x18\x04 \x01(\x03R\x0eenrolledAtUnix\x123\n" +
	"\x16last_evaluated_at_unix\x18\x05 \x01(\x03R\x13lastEvaluatedAtUnix\x12%\n" +
	"\x0estatus_message\x18\x06 \x01(\tR\rstatusMessage2Q\n" +
	"\x10SpeculateService\x12=\n" +
	"\x06Enroll\x12\x18.speculate.EnrollRequest\x1a\x19.speculate.EnrollResponseB)Z'github.com/brotherlogic/speculate/protob\x06proto3"

var (
	file_proto_speculate_proto_rawDescOnce sync.Once
	file_proto_speculate_proto_rawDescData []byte
)

func file_proto_speculate_proto_rawDescGZIP() []byte {
	file_proto_speculate_proto_rawDescOnce.Do(func() {
		file_proto_speculate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_speculate_proto_rawDesc), len(file_proto_speculate_proto_rawDesc)))
	})
	return file_proto_speculate_proto_rawDescData
}

var file_proto_speculate_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_speculate_proto_goTypes = []any{
	(*EnrollRequest)(nil),    // 0: speculate.EnrollRequest
	(*EnrollResponse)(nil),   // 1: speculate.EnrollResponse
	(*EnrollmentRecord)(nil), // 2: speculate.EnrollmentRecord
}
var file_proto_speculate_proto_depIdxs = []int32{
	0, // 0: speculate.SpeculateService.Enroll:input_type -> speculate.EnrollRequest
	1, // 1: speculate.SpeculateService.Enroll:output_type -> speculate.EnrollResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_speculate_proto_init() }
func file_proto_speculate_proto_init() {
	if File_proto_speculate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_speculate_proto_rawDesc), len(file_proto_speculate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_speculate_proto_goTypes,
		DependencyIndexes: file_proto_speculate_proto_depIdxs,
		MessageInfos:      file_proto_speculate_proto_msgTypes,
	}.Build()
	File_proto_speculate_proto = out.File
	file_proto_speculate_proto_goTypes = nil
	file_proto_speculate_proto_depIdxs = nil
}
