// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: proto/speculate.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeculateService_Enroll_FullMethodName = "/speculate.SpeculateService/Enroll"
)

// SpeculateServiceClient is the client API for SpeculateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpeculateService manages repository enrollment and alignment tracking.
type SpeculateServiceClient interface {
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
}

type speculateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeculateServiceClient(cc grpc.ClientConnInterface) SpeculateServiceClient {
	return &speculateServiceClient{cc}
}

func (c *speculateServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, SpeculateService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpeculateServiceServer is the server API for SpeculateService service.
// All implementations must embed UnimplementedSpeculateServiceServer
// for forward compatibility.
//
// SpeculateService manages repository enrollment and alignment tracking.
type SpeculateServiceServer interface {
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	mustEmbedUnimplementedSpeculateServiceServer()
}

// UnimplementedSpeculateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeculateServiceServer struct{}

func (UnimplementedSpeculateServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedSpeculateServiceServer) mustEmbedUnimplementedSpeculateServiceServer() {}
func (UnimplementedSpeculateServiceServer) testEmbeddedByValue()                          {}

// UnsafeSpeculateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeculateServiceServer will
// result in compilation errors.
type UnsafeSpeculateServiceServer interface {
	mustEmbedUnimplementedSpeculateServiceServer()
}

func RegisterSpeculateServiceServer(s grpc.ServiceRegistrar, srv SpeculateServiceServer) {
	// If the following call panics, it indicates UnimplementedSpeculateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeculateService_ServiceDesc, srv)
}

func _SpeculateService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpeculateServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SpeculateService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpeculateServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SpeculateService_ServiceDesc is the grpc.ServiceDesc for SpeculateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeculateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speculate.SpeculateService",
	HandlerType: (*SpeculateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _SpeculateService_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/speculate.proto",
}
